#!/bin/bash
# -*- coding: utf-8 -*-

# initproject: OmegaT label-enabling project init script.
# Copyright (C): 2016, Ramiro Duarte Simoes Lopes
#
# This file is part of LabelEnable OmegaT
#
# initproject is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Call argument: OmegaT project path: project/foo
path_project=$1

project=${path_project##*/}
text=$(<${path_project}/omegat.project)
source_lang=${text##*<source_lang>}
source_lang=${source_lang%%<*}
target_lang=${text##*<target_lang>}
target_lang=${target_lang%%<*}
lang_pair=${source_lang}_${target_lang}
lang_pair=${lang_pair,,}

for label in "$path_project"/label/*; do
  label=${label##*/}
  if [[ -d label/$lang_pair/$label ]]; then
    for file_tmx in label/"$lang_pair"/"$label"/tm/*; do
      if [[ ${file_tmx##*/} != ${project}-omegat.tmx ]]; then
        ln -f "$file_tmx" "$path_project"/tm/
      fi
    done
    if [[ -f label/"$lang_pair"/"$label"/glossary/"$label".txt ]]; then
      ln -f label/"$lang_pair"/"$label"/glossary/"$label".txt \
        "$path_project"/glossary/
    fi
  fi
done
